const fs = require('fs');
const path = require('path');
const matter = require('gray-matter');

function parseMarkdownFiles(dir) {
  const files = fs.readdirSync(dir);
  const data = files.map(filename => {
    const filePath = path.join(dir, filename);
    const fileContent = fs.readFileSync(filePath, 'utf-8');
    const { data: frontmatter, content } = matter(fileContent);
    return { ...frontmatter, description: content.trim() };
  });
  return data;
}

function generateDataFile(jobs, testimonials) {
  const content = `// This file is auto-generated by generateData.js
export const jobs = ${JSON.stringify(jobs, null, 2)};
export const testimonials = ${JSON.stringify(testimonials, null, 2)};
`;
  fs.writeFileSync(path.join(__dirname, 'js', 'data.js'), content, 'utf-8');
  console.log('Data file generated at js/data.js');
}

function main() {
  const jobsDir = path.join(__dirname, 'content', 'jobs');
  const testimonialsDir = path.join(__dirname, 'content', 'testimonials');

  const jobs = parseMarkdownFiles(jobsDir);
  const testimonials = parseMarkdownFiles(testimonialsDir);

  generateDataFile(jobs, testimonials);
}

main();
