backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "jobs"
    label: "Lowongan Kerja"
    folder: "content/jobs"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Judul Posisi", name: "title", widget: "string"}
      - {label: "Perusahaan", name: "company", widget: "string"}
      - {label: "Lokasi", name: "location", widget: "string"}
      - {label: "Tipe Pekerjaan", name: "type", widget: "select", options: ["Full Time", "Part Time", "Contract", "Internship"]}
      - {label: "Gaji", name: "salary", widget: "string"}
      - {label: "Deskripsi Pekerjaan", name: "description", widget: "text"}
      - {label: "Persyaratan", name: "requirements", widget: "list"}
      - {label: "Benefit", name: "benefits", widget: "list"}
      - {label: "Tanggal Diposting", name: "date", widget: "datetime"}
      - {label: "Status", name: "status", widget: "select", options: ["Open", "Closed"], default: "Open"}
      - {label: "Gambar", name: "image", widget: "image", required: false}

  - name: "testimonials"
    label: "Testimoni"
    folder: "content/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Nama Pelaut", name: "name", widget: "string"}
      - {label: "Posisi/Jabatan", name: "position", widget: "string"}
      - {label: "Foto", name: "image", widget: "image", required: false}
      - {label: "Testimoni", name: "text", widget: "text"}
      - {label: "Rating", name: "rating", widget: "number", value_type: "int", min: 1, max: 5, default: 5}
      - {label: "Tanggal", name: "date", widget: "datetime"}

  - name: "settings"
    label: "Pengaturan Website"
    files:
      - name: "general"
        label: "Pengaturan Umum"
        file: "content/settings/general.json"
        fields:
          - {label: "Nama Perusahaan", name: "company_name", widget: "string"}
          - {label: "Tagline", name: "tagline", widget: "string"}
          - {label: "Alamat", name: "address", widget: "text"}
          - {label: "Telepon", name: "phone", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Jam Kerja", name: "working_hours", widget: "string"}
          - {label: "Logo", name: "logo", widget: "image"}
          - {label: "Meta Description", name: "meta_description", widget: "text"}
          - {label: "Meta Keywords", name: "meta_keywords", widget: "list"}

  - name: "pages"
    label: "Halaman"
    files:
      - name: "about"
        label: "Tentang Kami"
        file: "content/pages/about.md"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Konten", name: "body", widget: "markdown"}
          - {label: "Gambar", name: "image", widget: "image", required: false}
